### PR TITLE
Added ability to pick board directory

### PR DESCRIPTION
**Pull request by rijesha**
I added the ability to choose a board directory each time change board is called.

### CODE REVIEW

**Comment by jaredwolff** [comment]
@rijesha thanks for the submission. I guess it's not clear what you're trying to accomplish here. It breaks the original functionality of parsing Zephyr's `boards` directory.

**Comment by rijesha** [comment]
So there are a couple of problems I was trying to address.

I did manage to put a custom board directory in my app folder. When I did that the existing code showed me a list of my custom boards. When I went to build I got an error saying that the board doesn't exist is the default zephyr board directory. So to fix that I added the board_root_dir. This variable is passed into the west command. 

This code still allows parsing the zephyr boards directory. When run the code looks for board directories in the root directory, application directory and in the zephyr directory. (assuming the zephyr directory is located in a subfolder of root) The user selects the board directory and then selects the board they want to use from that directory.

**Comment by jaredwolff** [comment]
> This code still allows parsing the zephyr boards directory. When run the code looks for board directories in the root directory, application directory and in the zephyr directory. (assuming the zephyr directory is located in a subfolder of root) The user selects the board directory and then selects the board they want to use from that directory.

Not when I tested it. Did you test on all 3 platforms to confirm? Does not work on Linux.

**Comment by rijesha** [comment]
Hmm. I only tested on windows. I can try it out on linux and see whats up.

As an aside, the release on the visual studio marketplace, didn't allow me to select any boards from the zephyr directory. (Essentially I couldn't select a zephyr board, because none were populating in the list, and when I had a custom board directory in the app folder, I was able to select a board, but that board directory was not being passed into the west command. So essentially I wasn't able to build anything with the extension.)

**Comment by rijesha** [comment]
So it seems to work on linux for me. I was running linux on a vm, so it was slow (~40s) for the full list of zephyr boards to load. (I don't think the slowness is from the code I added as the getBoardlist function is the same.)

The board directory that was in the app/project directory initially failed to parse, due to the project variable not being initialized. (It got initialized once after I ran change project or build and then started working)

Screenshot 2024-03-29 215742
Screenshot 2024-03-29 215849

**Comment by rijesha** [comment]
So looking at the original code the directory structure had to be like the following and this is what you have that is no longer working. (Please correct me if I am wrong)
```
root (or app)
  - app
  - zephyr
    - boards
```

My directory structure is the following:
```
root
  - boards
  - app
    - boards 
  - deps
    - zephyr
      - boards
```

I'll push an update to recursively look for board directories one folder down from root. (This will also solve the problem of a board directory within a project not being found if the project has yet to be initialized)

**Comment by rijesha** [comment]
Closing this, as no updates and seems to break existing functionality.

**Pull request closed without merging**
